services:
  labs-challenge-api:
    build: .
    container_name: labs_challenge_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
    depends_on:
      - sql-server-db
      - elasticsearch
    ports:
      - "8081:8081"

  sql-server-db:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: sql_server_db
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Magazine123
      ports:
        - "1433:1433"
      volumes:
        - ./init/mssqlsettings:/docker-entrypoint-initdb.d:z
      entrypoint: ["/bin/bash", "-c", "/docker-entrypoint-initdb.d/configure-db.sh & /opt/mssql/bin/sqlservr"]
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    depends_on:
      - elasticsearch

volumes:
  esdata: